[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd bwcrackers && npm install"]

[phases.build]
cmds = ["cd bwcrackers && npx medusa build"]

[start]
cmd = "cd bwcrackers && npx medusa start"
