-- B&W Crackers — core schema: catalog, customers, orders, settings, admins.
-- Public visitors can read the active catalog and settings. Everything about
-- customers and orders is admin-only; the storefront writes orders through a
-- server route that uses the service-role key.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- helpers --

create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ----------------------------------------------------------------- admins --

create table if not exists public.admins (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  name       text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

-- ---------------------------------------------------------------- catalog --

create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  name        text not null,
  slug        text not null unique,
  sort_order  int  not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.products (
  id           bigint generated by default as identity primary key,
  code         text not null unique,                       -- price-list number, e.g. "1", "FP1"
  name         text not null,
  category_id  bigint not null references public.categories(id) on delete restrict,
  unit         text not null default '1 BOX',
  mrp          numeric(10,2) not null default 0 check (mrp >= 0),
  price        numeric(10,2) not null default 0 check (price >= 0),
  image_url    text,
  gallery      text[] not null default '{}',
  description  text,
  is_active    boolean not null default true,              -- shown on the website
  in_stock     boolean not null default true,
  is_premium   boolean not null default false,
  sort_order   int not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists products_category_idx on public.products (category_id, sort_order);

-- -------------------------------------------------------------- customers --

create table if not exists public.customers (
  id          uuid primary key default gen_random_uuid(),
  phone       text not null unique,                        -- +91XXXXXXXXXX
  name        text not null,
  email       text,
  address     text,
  city        text,
  state       text,
  pincode     text,
  admin_notes text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ----------------------------------------------------------------- orders --

do $$ begin
  create type public.order_status as enum
    ('pending', 'confirmed', 'paid', 'packed', 'dispatched', 'delivered', 'cancelled');
exception when duplicate_object then null; end $$;

create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),
  reference       text not null unique,                    -- customer-facing, e.g. BW7K2Q9P
  customer_id     uuid references public.customers(id) on delete set null,
  -- Snapshot of the customer's details at order time.
  customer_name   text not null,
  phone           text not null,
  email           text,
  address         text,
  city            text,
  state           text,
  pincode         text,
  customer_notes  text,
  subtotal        numeric(12,2) not null,
  mrp_total       numeric(12,2) not null default 0,
  packing_fee     numeric(12,2) not null default 0,
  grand_total     numeric(12,2) not null,
  status          public.order_status not null default 'pending',
  amount_paid     numeric(12,2) not null default 0,
  transporter     text,
  tracking_number text,
  admin_notes     text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_customer_idx on public.orders (customer_id);

create table if not exists public.order_items (
  id          bigint generated by default as identity primary key,
  order_id    uuid not null references public.orders(id) on delete cascade,
  product_id  bigint references public.products(id) on delete set null,
  code        text not null,
  name        text not null,
  unit        text,
  mrp         numeric(10,2) not null default 0,
  price       numeric(10,2) not null,
  quantity    int not null check (quantity > 0),
  line_total  numeric(12,2) not null
);
create index if not exists order_items_order_idx on public.order_items (order_id);

create table if not exists public.order_events (
  id          bigint generated by default as identity primary key,
  order_id    uuid not null references public.orders(id) on delete cascade,
  status      public.order_status,
  note        text,
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index if not exists order_events_order_idx on public.order_events (order_id, created_at);

-- --------------------------------------------------------------- settings --

create table if not exists public.settings (
  id          int primary key default 1 check (id = 1),
  data        jsonb not null default '{}',
  updated_at  timestamptz not null default now()
);
insert into public.settings (id, data) values (1, '{}') on conflict (id) do nothing;

-- ---------------------------------------------------------------- triggers --

do $$
declare t text;
begin
  foreach t in array array['categories', 'products', 'customers', 'orders', 'settings'] loop
    execute format('drop trigger if exists %I_updated_at on public.%I', t, t);
    execute format('create trigger %I_updated_at before update on public.%I
                    for each row execute function public.set_updated_at()', t, t);
  end loop;
end $$;

-- --------------------------------------------------------- row-level security --

alter table public.admins       enable row level security;
alter table public.categories   enable row level security;
alter table public.products     enable row level security;
alter table public.customers    enable row level security;
alter table public.orders       enable row level security;
alter table public.order_items  enable row level security;
alter table public.order_events enable row level security;
alter table public.settings     enable row level security;

drop policy if exists "admins read own" on public.admins;
create policy "admins read own" on public.admins for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists "public read active categories" on public.categories;
create policy "public read active categories" on public.categories for select using (is_active or public.is_admin());
drop policy if exists "admin write categories" on public.categories;
create policy "admin write categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products for select using (is_active or public.is_admin());
drop policy if exists "admin write products" on public.products;
create policy "admin write products" on public.products for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read settings" on public.settings;
create policy "public read settings" on public.settings for select using (true);
drop policy if exists "admin write settings" on public.settings;
create policy "admin write settings" on public.settings for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin all customers" on public.customers;
create policy "admin all customers" on public.customers for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin all orders" on public.orders;
create policy "admin all orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin all order items" on public.order_items;
create policy "admin all order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin all order events" on public.order_events;
create policy "admin all order events" on public.order_events for all using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------- storage --

insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects for select using (bucket_id = 'products');
drop policy if exists "admin upload product images" on storage.objects;
create policy "admin upload product images" on storage.objects for insert with check (bucket_id = 'products' and public.is_admin());
drop policy if exists "admin update product images" on storage.objects;
create policy "admin update product images" on storage.objects for update using (bucket_id = 'products' and public.is_admin());
drop policy if exists "admin delete product images" on storage.objects;
create policy "admin delete product images" on storage.objects for delete using (bucket_id = 'products' and public.is_admin());
